name: docker-build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 * * *"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest ternoa release
        id: ternoa
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: capsule-corp-ternoa/ternoa-node 
          draft: false
          prerelease: false
          latest: true
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
          
      - name: Check image tag exists
        id: image_exists
        continue-on-error: true 
        uses: cloudposse/github-action-docker-image-exists@main
        with:
            registry: quay.io
            organization: andrijdavid
            repository: ternoa-node
            login: ${{ secrets.QUAYIO_USERNAME }}
            password: ${{ secrets.QUAYIO_TOKEN }}
            tag: ${{ steps.split.outputs.fragment }}
      -
        name: Set up QEMU
        if: steps.image_exists.outcome != 'success'
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Set up Docker Buildx
        if: steps.image_exists.outcome != 'success'
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        if: steps.image_exists.outcome != 'success'
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: quay.io/andrijdavid/ternoa-node:latest, quay.io/andrijdavid/ternoa-node:${{ steps.split.outputs.fragment }}, quay.io/andrijdavid/ternoa-node:${{ steps.nym.outputs.tag_name }}
          build-args: |
            VER=${{ steps.split.outputs.fragment }}
          